### ISSUE TITLE
Node version 5 doesn't  find ULokcs

### ISSUE THREAD

**Issue by nopbyte** [SEDARI/UPFROnt#2]
This doesn't really affect AGILE since we run on node v7. However, travis found out that on version 5 of Node, ULocks is not found.

In the case of AGILE IDM, this was solved if I add ULocks as a dependency in IDM, although IDM does not call ULocks on its own ever... 

The funny issue is that this only happens with version 5. It seems with other versions it works OK. I guess we are on our way to find new beauties of JavaScript and Node if this is to be solved.

The error is the following:

```
    throw err;
    ^

Error: Cannot find module 'ULocks'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/UPFROnt/pdp/api/index.js:5:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/UPFROnt/pdp/index.js:1:73)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by dschrecking** [comment]
Changed package name ulocks to ULocks in package.json such that v5 will actually load it.
